name: Tweak Inject
targets:
  Tweak Inject:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [My App, Resources]
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.AppInstalleriOS.Tweak-Inject
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        SWIFT_OBJC_BRIDGING_HEADER: My App/TSUtil.h
